spring:
  application:
    name: service
  datasource:
    url:  jdbc:postgresql://localhost:5432/join-promise
    username: postgres
    password: password

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml